# Generated by Django 5.0.6 on 2024-05-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('FEDM', 'Федеральный руководитель'), ('REGM', 'Региональный руководитель'), ('USER', 'Пользователь')], default='USER', max_length=4, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
