# Generated by Django 5.0.6 on 2024-05-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_status_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=150, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
