# Generated by Django 5.0.6 on 2024-05-11 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
        ('employees', '0001_initial'),
        ('info', '0001_initial'),
        ('media_content', '0001_initial'),
        ('regional_offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('website', models.URLField(verbose_name='Ссылка на сайт')),
                ('disciplines', models.ManyToManyField(related_name='events', to='info.discipline', verbose_name='Дисциплины')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='employees.regionalmanager', verbose_name='Сотрудник')),
                ('gallery', models.ManyToManyField(to='media_content.image', verbose_name='Галерея')),
                ('partners', models.ManyToManyField(blank=True, related_name='events', to='about.partner', verbose_name='Партнеры')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='regional_offices.region', verbose_name='Регион')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_content.video', to_field='video', verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
