# Generated by Django 5.0.6 on 2024-05-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_partner_options_alter_partner_type'),
        ('employees', '0002_alter_regionalmanager_options_and_more'),
        ('events', '0001_initial'),
        ('info', '0002_alter_interview_options_alter_article_discipline_and_more'),
        ('regional_offices', '0002_alter_spot_options_alter_spot_discipline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_related_name': 'events', 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='event',
            name='disciplines',
            field=models.ManyToManyField(to='info.discipline', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.regionalmanager', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(blank=True, to='about.partner', verbose_name='Партнеры'),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_offices.region', verbose_name='Регион'),
        ),
    ]
