# Generated by Django 5.0.6 on 2024-05-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
