# Generated by Django 5.0.6 on 2024-05-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0002_alter_image_options_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
