# Generated by Django 5.0.6 on 2024-05-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("about", "0001_initial"),
        ("regional_offices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "preview",
                    models.ImageField(upload_to="images/", verbose_name="Изображение"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата и время")),
                ("end_date", models.DateTimeField(verbose_name="Дата и время")),
                (
                    "funds_raised",
                    models.IntegerField(verbose_name="Объем финансирования"),
                ),
                ("goal", models.IntegerField(verbose_name="Цель")),
                (
                    "partners",
                    models.ManyToManyField(
                        blank=True, to="about.partner", verbose_name="Партнеры"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regional_offices.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "default_related_name": "projects",
            },
        ),
    ]
