# Generated by Django 5.0.6 on 2024-05-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("current", "Текущий"),
                    ("future", "Предстоящий"),
                    ("done", "Выполненный"),
                ],
                default="future",
                max_length=8,
                verbose_name="Статус",
            ),
        ),
    ]
