# Generated by Django 5.0.6 on 2024-05-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_status_project_done_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="done",
            new_name="is_finished",
        ),
    ]
