FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt --no-cache-dir
RUN python3 manage.py migrate
RUN python3 manage.py collectstatic --no-input
RUN echo "from users.models import User; User.objects.create_superuser('admin', 'admin@m.ru', 'admin')" | python3 manage.py shell
CMD ["python3", "manage.py", "runserver", "0:8000", "--insecure"]