# Generated by Django 5.0.6 on 2024-05-11 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('media_content', '0001_initial'),
        ('regional_offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('career_start', models.DateField(verbose_name='Начало карьеры')),
                ('citi_of_birth', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('vk_page', models.URLField(blank=True, verbose_name='Страница Вконтакте')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('tel', models.CharField(max_length=12, verbose_name='Телефон')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_content.image', to_field='image', verbose_name='Банер')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='info.discipline', verbose_name='Дисциплина')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_content.image', to_field='image', verbose_name='Фото')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_content.video', to_field='video', verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Федеральный руководитель',
                'verbose_name_plural': 'Федеральное руководство',
            },
        ),
        migrations.CreateModel(
            name='RegionalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('career_start', models.DateField(verbose_name='Начало карьеры')),
                ('citi_of_birth', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('vk_page', models.URLField(blank=True, verbose_name='Страница Вконтакте')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('tel', models.CharField(max_length=12, verbose_name='Телефон')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_content.image', to_field='image', verbose_name='Банер')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='info.discipline', verbose_name='Дисциплина')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_content.image', to_field='image', verbose_name='Фото')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='regional_offices.region', verbose_name='Регион')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_content.video', to_field='video', verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Региональный руководитель',
                'verbose_name_plural': 'Региональное руководство',
            },
        ),
    ]
