# Generated by Django 5.0.6 on 2024-05-21 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('tel', models.CharField(max_length=12, verbose_name='Телефон')),
                ('actual_address', models.CharField(max_length=255, verbose_name='Фактический адрес')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип партнерства',
                'verbose_name_plural': 'Типы партнерства',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('website', models.URLField(verbose_name='Ссылка на сайт')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='Логотип')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.partnertype', verbose_name='Тип партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'default_related_name': 'partners',
            },
        ),
    ]
