# Generated by Django 5.0.6 on 2024-05-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'default_related_name': 'partners', 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.partnertype', verbose_name='Тип партнера'),
        ),
    ]
