# Generated by Django 5.0.6 on 2024-05-11 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('media_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Citi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='regional_offices.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('spot_type', models.CharField(choices=[('OP', 'Уличные локации'), ('CL', 'Крытые локации')], max_length=2, verbose_name='Тип локации')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('website', models.URLField(verbose_name='Ссылка на сайт')),
                ('citi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='regional_offices.citi', verbose_name='Город')),
                ('discipline', models.ManyToManyField(related_name='spots', to='info.discipline', verbose_name='Дисциплина')),
                ('gallery', models.ManyToManyField(to='media_content.image', verbose_name='Галерея')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='regional_offices.region', verbose_name='Регион')),
                ('videos', models.ManyToManyField(blank=True, to='media_content.video', verbose_name='Ссылки на видео')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
    ]
