# Generated by Django 5.0.6 on 2024-05-21 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
        ('employees', '0001_initial'),
        ('info', '0001_initial'),
        ('media_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('website', models.URLField(verbose_name='Ссылка на сайт')),
                ('preview', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('disciplines', models.ManyToManyField(to='info.discipline', verbose_name='Дисциплины')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.regionalmanager', verbose_name='Сотрудник')),
                ('partners', models.ManyToManyField(blank=True, to='about.partner', verbose_name='Партнеры')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_offices.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'default_related_name': 'events',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_offices.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'default_related_name': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('spot_type', models.CharField(choices=[('OP', 'Уличные локации'), ('CL', 'Крытые локации')], max_length=2, verbose_name='Тип локации')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('website', models.URLField(verbose_name='Ссылка на сайт')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_offices.city', verbose_name='Город')),
                ('discipline', models.ManyToManyField(to='info.discipline', verbose_name='Дисциплина')),
                ('gallery', models.ManyToManyField(to='media_content.image', verbose_name='Галерея')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_offices.region', verbose_name='Регион')),
                ('videos', models.ManyToManyField(blank=True, to='media_content.video', verbose_name='Ссылки на видео')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'default_related_name': 'spots',
            },
        ),
    ]
