# Generated by Django 5.0.6 on 2024-05-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regional_offices", "0002_alter_event_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spot",
            name="region",
        ),
        migrations.AddField(
            model_name="spot",
            name="coordinates",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Координаты"
            ),
        ),
    ]
