# Generated by Django 5.0.6 on 2024-05-11 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_partner_options_alter_partner_type'),
        ('employees', '0002_alter_regionalmanager_options_and_more'),
        ('info', '0002_alter_interview_options_alter_article_discipline_and_more'),
        ('media_content', '0003_alter_image_options_alter_video_options'),
        ('regional_offices', '0003_alter_citi_options_alter_citi_region_alter_spot_citi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('website', models.URLField(verbose_name='Ссылка на сайт')),
                ('disciplines', models.ManyToManyField(to='info.discipline', verbose_name='Дисциплины')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.regionalmanager', verbose_name='Сотрудник')),
                ('gallery', models.ManyToManyField(to='media_content.image', verbose_name='Галерея')),
                ('partners', models.ManyToManyField(blank=True, to='about.partner', verbose_name='Партнеры')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_offices.region', verbose_name='Регион')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_content.video', to_field='video', verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'default_related_name': 'events',
            },
        ),
    ]
